### ISSUE TITLE
Negative values not appearing

### ISSUE THREAD

**Issue by johnbde** [eurostat/restatapi#1]
Negative values not appearing in GDP. For the last 2 quarters it should be negative for spain.

```
t <- restatapi::get_eurostat_data("namq_10_gdp")
t %>% dplyr::filter(na_item == "B1GQ") %>% filter(geo == "ES") %>% filter(unit == "CLV_PCH_PRE")

```

**Comment by mmatyi** [comment]
thanks for the report, it is corrected now in the 0.8.10
but you can do quicker if you do not download the whole dataset but filter in the query.

`t <- restatapi::get_eurostat_data("namq_10_gdp",filters=c("ES","CLV_PCH_PRE","B1GQ"))`
