### ISSUE TITLE
Applying "filters" argument to get_eurostat_data() results in error for some datasets

### ISSUE THREAD

**Issue by mhwachter** [eurostat/restatapi#11]
**Describe the bug**
get_eurostat_data() with "filters" argument throws error "Problem by the extraction of the footer information from the xml_file.
404 - No data retrived with the given filter(s)" for some datasets.

**To Reproduce**
```
library(restatapi)
df <- get_eurostat_data(id = "sbs_sc_ind_r2", filters = list(geo = "AT"), keep_flags = TRUE)
```

**Expected behavior**
It should work the same way as it does for other datasets:
```
library(restatapi)
df <- get_eurostat_data(id = "sbs_sc_dt_r2", filters = list(geo = "AT"), keep_flags = TRUE)
```

**Desktop:**
 - OS: Win10
 - R version: 4.3.0 (64-bit)
 - restatapi version: 0.20.6

**Comment by mmatyi** [comment]
Hello, thank you for your feedback, the bug is corrected in version 0.22.0.  

You might consider to use the force_local_filter=TRUE option because the filtered dataset is quite big to use with SDMX-XML.

```
library(restatapi)
df <- get_eurostat_data(id = "sbs_sc_dt_r2", filters = list(geo = "AT"), keep_flags = TRUE, force_local_filter=TRUE)
```
