### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kubocery** [eurostat/restatapi#5]
It seems that the whole Eurostat API was changed, none of the functions from the packages `eurostat` and `restatapi` work, as they throw an `error 404`. 

Examples:
`get_eurostat_toc()`
results in
`Error in open.connection(5L, "rb") : cannot open the connection
In addition: Warning message:
In open.connection(5L, "rb") :
  cannot open URL 'https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&downfile=table_of_contents_en.txt': HTTP status was '404 '`

`R 4.1.0`
`restatapi 0.12.3`

Same issue is with the `eurostat` package. Is there any possibility to fix the `restatapi` package to make it work? Thank you!

**Comment by mmatyi** [comment]
hello, 

it looks like it was a temporary issue with the Eurostat server. Now it works correctly.
